[build]
  publish = "site"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/now-playing"
  to = "/.netlify/functions/nowplaying"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
